### ISSUE TITLE
C++11 

### ISSUE THREAD

**Issue by dmitrySorokin** [ivannz/rlplay#1]
I got a compilation error at MacOS. To fix it compile with c++11 (at least) to support initializer list syntax in pyrl. 

setup.py: 
```
ext_modules=[
         Extension(
             'rlplay.engine.utils.plyr', [
                 'rlplay/engine/utils/plyr/plyr.cpp',
                 'rlplay/engine/utils/plyr/validate.cpp',
                 'rlplay/engine/utils/plyr/operations.cpp',
                 'rlplay/engine/utils/plyr/apply.cpp',
             ], include_dirs=[
                 'rlplay/engine/utils/plyr/include'
             ], extra_compile_args=[
                 '-O3', '-Ofast', '-std=c++11'
             ], language='c++',
         ),
     ],

```

**Comment by ivannz** [comment]
I have decided that vendoring an independently useful nested container mapper in `rlplay` is suboptimal. About a month ago i forked `plyr` into a dedicated package `https://gtihub.com/ivannz/plyr`, which is also available on pypi. Development of `plyr` in `rlplay` has been discontinued, and will soon be completely removed from this package.
